### ISSUE TITLE
Error on code completion

### ISSUE THREAD

**Issue by stardiviner** [emacs-eclim/emacs-eclim#11]
I got the following error in Emacs `*Messages*` buffer.

```
Company: backend (company-emacs-eclim :with company-yasnippet) error "java.lang.RuntimeException: No command ’java_complete’ found.
    at org.eclim.command.Options.parse(Options.java:178)
    at org.eclim.command.Main.nailMain(Main.java:87)
    at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.martiansoftware.nailgun.NGSession.run(NGSession.java:336)
" with args (candidates out)
```

And I tested, Eclipse works correctly.
And my version info:
- Emacs: 25.1.50.30
- eclim: 2.6.0.1 (installed from Arch Linux AUR)

**Comment by stardiviner** [comment]
Problem is solved by re-install eclim.
