### ISSUE TITLE
Wrong path when invoke eclim.bat on Windows 10

### ISSUE THREAD

**Issue by AlohaWorld** [emacs-eclim/emacs-eclim#12]
**OS:** 
    Windows 10, x64

**Eclipse:**
    Version: Neon Release (4.6.0) x64
    Build id: 20160613-1800

**eclim:**
    2.6.0

**Emacs:**
    GNU Emacs 24.5.1 (i686-pc-mingw32)
    with spacemacs 0.105.22

**Description:**
  When saving the java source file in Emacs, eclim.bat is triggered. Then eclimd gives error messages (please see "Error Message" in the following section) 

  By adding "echo" command in eclim.bat, I can see the args that Emacs give to eclim.bat, "%*" is

```
-command project_by_resource -f d\:/MyDocument/10.Teaching/Classes/Java/src/u01/Welcome.java 
```

  where in the path of the source file "Welcome.java" there is a "d\:", which is an obvious error. The correct one should be "d:" without "\"

  Then I searched "project_by_resource" in emacs-eclim package and found that in `eclim-common.el` line 232, there is a statement:

`(eclim/execute-command "project_by_resource" ("-f" file))))`

  However, due to my limit elisp knowledge, I have no idea with this statement.
  Is there anyone can solve this problem?

**Error Message:**

```
2016-09-11 18:26:17,806 ERROR [org.eclim.command.Main] Command failed
java.net.URISyntaxException: Illegal character in authority at index 7: file://d\:/MyDocument/10.Teaching/Classes/Java/src/u01/Welcome.java
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.parseAuthority(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at org.eclim.plugin.core.command.project.ProjectByResource.execute(ProjectByResource.java:56)
        at org.eclim.command.Main$1.run(Main.java:100)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3819)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
        at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:128)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
NGSession 2: 127.0.0.1: org.eclim.command.Main exited with status 1
```

**Comment by nloyola** [comment]
Would `d\:` come from one of your environment variables? Or from the way you defined your Eclipse project?

I'm using Linux, but in Emacs if I type <kbd>M-:</kbd> `(buffer-file-name)`  it shows me the full path name for the buffer I'm visiting. This is the path being passed to the `eclim-project-name` function in `eclim-common.el` you mentioned.

**Comment by nloyola** [comment]
Closing this since there has been no feedback. Issue can be re-opened at a later time.
